"""added status to order_detail

Revision ID: 0fb0d516aa0f
Revises: 51b0a6ad9c27
Create Date: 2023-11-23 19:09:43.771016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb0d516aa0f'
down_revision = '51b0a6ad9c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=12), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
