"""create user and role

Revision ID: cfa4c171a601
Revises: 
Create Date: 2023-11-09 16:22:27.804747

"""
from alembic import op
import sqlalchemy as sa
from uuid import uuid4
from datetime import datetime
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'cfa4c171a601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    role_table = table(
        'role',
        column('id', sa.UUID),
        column('title', sa.String),
        column('created_at', sa.DateTime),
        column('modified_at', sa.DateTime),
    )

    op.bulk_insert(
        role_table,
        [
            {
                'id': uuid4(),
                'title': 'admin',
                'created_at': datetime.utcnow(),
                'modified_at': datetime.utcnow(),
            },
            {
                'id': uuid4(),
                'title': 'customer',
                'created_at': datetime.utcnow(),
                'modified_at': datetime.utcnow(),
            },
            {
                'id': uuid4(),
                'title': 'vendor',
                'created_at': datetime.utcnow(),
                'modified_at': datetime.utcnow(),
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
